site_name: Metrist
site_url: https://docs.metrist.io
extra_css:
    - custom.css
pages:
    - Home: 'index.md'
    - 'Chat Apps':
      - Slack: 'slack.md'
      - Teams: 'teams.md'
    - 'Web App':
      - 'Inviting your team': 'web-app-invites.md'
      - 'Configuring service montiors': 'web-app-monitors.md'
      - 'Configuring notifications': 'web-app-notifications.md'
      - 'Configuring thresholds': 'web-app-thresholds.md'
    - 'Agent':
      - 'General overview': 'agent-overview.md'
      - 'Agent source code': 'agent-source-code.md'
      - 'Ruby in-process agent': 'agent-ruby-in-process.md'
      - 'PHP/Curl in-process agent': 'agent-php-in-process.md'
