site_name: Metrist
site_url: https://docs.metrist.io
extra_css:
    - custom.css
nav:
    - Home: 'index.md'
    - 'Chat Apps':
      - Slack: 'slack.md'
    - 'Web App':
      - 'Inviting your team': 'web-app-invites.md'
      - 'Configuring service montiors': 'web-app-monitors.md'
      - 'Configuring notifications': 'web-app-notifications.md'
      - 'Configuring thresholds': 'web-app-thresholds.md'
    - 'Download':
      - 'General overview': 'download-overview.md'
      - 'Installation': 'orchestrator-installation.md'
      - 'Orchestrator source code': 'orchestrator-source-code.md'
      - 'Ruby in-process agent': 'agent-ruby-in-process.md'
      - 'PHP/Curl in-process agent': 'agent-php-in-process.md'
      - 'eBPF plugin': 'orchestrator-ebpf-plugin.md'
    - 'API': 'api.md'
